DROP TABLE IF EXISTS Loan;
CREATE TABLE Loan (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 itemId INTEGER UNIQUE,
 checkoutDate TIMESTAMP,
 dueDate TIMESTAMP,
 FOREIGN KEY (itemId) REFERENCES Item(id)
 );
