DROP TABLE IF EXISTS Loanable;
CREATE TABLE Loanable (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 itemId INTEGER UNIQUE,
 checkoutDate TIMESTAMP,
 dueDate TIMESTAMP,
 FOREIGN KEY (itemId) REFERENCES Item(id)
 );
