DROP TABLE IF EXISTS LoanableItem;
CREATE TABLE LoanableItem (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 itemId INTEGER NOT NULL UNIQUE,
 userId INTEGER NOT NULL,
 FOREIGN KEY (itemId) REFERENCES Item(id),
 FOREIGN KEY (userId) REFERENCES User(id)
 );
