DROP TABLE IF EXISTS Loan;
CREATE TABLE Loan (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 itemID INTEGER UNIQUE,
 checkoutDate TIMESTAMP,
 dueDate TIMESTAMP,
 FOREIGN KEY (itemID) REFERENCES Item(id)
 );
