DROP TABLE IF EXISTS Transac;
CREATE TABLE Transac (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 itemId INTEGER NOT NULL UNIQUE,
 userId INTEGER NOT NULL UNIQUE,
 transactionType varchar(255),
 checkoutDate TIMESTAMP,
 dueDate TIMESTAMP,
 FOREIGN KEY (userId) REFERENCES User(id),
 FOREIGN KEY (itemId) REFERENCES Item(id)
 );
